### ISSUE TITLE
Family Provider Migration - Update for XP 1.14

### ISSUE THREAD

**Issue by phisco** [upbound/docs#276]
### URL
https://docs.upbound.io/providers/migration/#manual-migration

### What's Wrong?
The current migration process does not work anymore with XP 1.14, so we need to update the documentation to clearly specify the two procedures, based on the XP version being used.

See [here](https://github.com/crossplane/crossplane/issues/5082#issuecomment-1838638300) for the updated procedure for XP 1.14.

**Comment by ulucinar** [comment]
We had better also make sure that the changes we discussed are still applicable for the Crossplane versions `>=v1.12.1-0`. We will also need to adapt the migration plan generated via the [migration framework](https://github.com/crossplane/upjet/tree/main/pkg/migration).

**Comment by turkenh** [comment]
We discussed this with @ulucinar and agreed that we should first check if we can avoid the behavior change in Crossplane in an easy way. While the new procedure is simpler/easier, it would be good if could "still" support the old way so that we keep backward compatibility while moving to the new approach in the documentation and migration tooling. 

I'll check the package manager code to see whether this is feasible. I think this boils down to the question of, with the recent changes, can an inactive revision put itself as "an owner but not controller" to a CRD instead of just setting "controller to false" only if it exist as a controller. We would also need to handle certificate secrets gracefully so that an inactive revision could become healthy instead of erroring out.

**Comment by phisco** [comment]
We merged https://github.com/crossplane/crossplane/pull/5179, so this is not required anymore 🙏
